@JwtAuthApi_HostAddress = http://localhost:5555

GET {{JwtAuthApi_HostAddress}}/api/customer
Content-Type: application/json

###

GET {{JwtAuthApi_HostAddress}}/api/users/All
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXJid3I0dnZiODk0NSIsImp0aSI6Ijc0ZjA4N2Q0LTZlZjUtNDE4ZS04MGUxLWVjMmUxMmMwZTg2NCIsImlhdCI6IjE3MTg1MjUxMDciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkB0ZXN0LmNvbSIsInVzZXJfaWQiOiI2ZjZmNDIzMy1iNGY2LTRhNzUtYTI1Ny03NmI2YmFkZTBhMDciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcxODUyNTI4NywiaXNzIjoiRXhhbXBsZUlzc3VlciIsImF1ZCI6IlZhbGlkQXVkaWVuY2UifQ.rT2Sn1tOAfuv7jJYoWa5VGNUfc3ixb__ARWtoCvOztg

###

POST {{JwtAuthApi_HostAddress}}/api/users/Register
Content-Type: application/json

{
  "email": "user1@test.com",
  "username": "user1",
  "password": "user123",
  "role": "Admin",
  "hobby": "Reading"
}
###

POST {{JwtAuthApi_HostAddress}}/api/users/Login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "administrator"
}

###

GET {{JwtAuthApi_HostAddress}}/api/pages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXJid3I0dnZiODk0NSIsImp0aSI6IjhlNmUxNzhmLTIwY2YtNDJjMS05MDU5LWU4N2UzODJlYjYxOCIsImlhdCI6MTcxODQ3MDIyNCwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VyX2lkIjoiNmY2ZjQyMzMtYjRmNi00YTc1LWEyNTctNzZiNmJhZGUwYTA3IiwiaG9iYnkiOiIiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTg0NzAyMjQsImV4cCI6MTcxODQ3MjAyNCwiaXNzIjoiRXhhbXBsZUlzc3VlciIsImF1ZCI6IlZhbGlkQXVkaWVuY2UifQ.KbP2aV2rQrRIlM8MfLxa9Gy4yvKCZ1yC1CEtxgnBH-0

###

GET {{JwtAuthApi_HostAddress}}/api/pages/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXJid3I0dnZiODk0NSIsImp0aSI6IjhlNmUxNzhmLTIwY2YtNDJjMS05MDU5LWU4N2UzODJlYjYxOCIsImlhdCI6MTcxODQ3MDIyNCwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VyX2lkIjoiNmY2ZjQyMzMtYjRmNi00YTc1LWEyNTctNzZiNmJhZGUwYTA3IiwiaG9iYnkiOiIiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTg0NzAyMjQsImV4cCI6MTcxODQ3MjAyNCwiaXNzIjoiRXhhbXBsZUlzc3VlciIsImF1ZCI6IlZhbGlkQXVkaWVuY2UifQ.KbP2aV2rQrRIlM8MfLxa9Gy4yvKCZ1yC1CEtxgnBH-0

###

POST {{JwtAuthApi_HostAddress}}/api/pages/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDVoMDk4YmI4cmViZXJid3I0dnZiODk0NSIsImp0aSI6IjhlNmUxNzhmLTIwY2YtNDJjMS05MDU5LWU4N2UzODJlYjYxOCIsImlhdCI6MTcxODQ3MDIyNCwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VyX2lkIjoiNmY2ZjQyMzMtYjRmNi00YTc1LWEyNTctNzZiNmJhZGUwYTA3IiwiaG9iYnkiOiIiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MTg0NzAyMjQsImV4cCI6MTcxODQ3MjAyNCwiaXNzIjoiRXhhbXBsZUlzc3VlciIsImF1ZCI6IlZhbGlkQXVkaWVuY2UifQ.KbP2aV2rQrRIlM8MfLxa9Gy4yvKCZ1yC1CEtxgnBH-0

{
  "id": "1",
  "title": "title2",
  "body": "body2",
  "author": "author2"
}

###
